# Generated by Django 3.1.2 on 2020-10-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=350)),
                ('phone', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('des', models.TextField()),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('github', models.URLField()),
                ('linked', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'My profile',
                'ordering': ('-created',),
            },
        ),
    ]
