# Generated by Django 3.1.2 on 2020-10-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profile_cv',
        ),
        migrations.AlterModelOptions(
            name='profile_cv',
            options={'ordering': ('-created',)},
        ),
    ]
