# Generated by Django 3.1.2 on 2020-10-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0002_auto_20201001_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile_cv',
            options={'ordering': ('-created',), 'verbose_name': 'My profile'},
        ),
        migrations.AddField(
            model_name='profile_cv',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='Uploads/$y/avatar/'),
        ),
    ]
