# Generated by Django 3.1.2 on 2020-10-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0003_auto_20201001_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_cv',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='Uploads/avatar/'),
        ),
    ]
