# Generated by Django 3.1.2 on 2020-10-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0004_auto_20201001_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=300)),
                ('des', models.TextField()),
                ('time_line', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='profile_cv',
            name='experience',
            field=models.ManyToManyField(blank=True, related_name='my_experience', to='profile_cv.Experience'),
        ),
    ]
