# Generated by Django 3.1.2 on 2020-10-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0006_auto_20201001_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme_profile',
            options={'ordering': ('-created',), 'verbose_name': 'Theme'},
        ),
    ]
