# Generated by Django 3.1.2 on 2020-10-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0011_profile_cv_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_cv',
            name='education',
        ),
        migrations.AddField(
            model_name='education',
            name='subtitle',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
