# Generated by Django 3.1.2 on 2020-10-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0013_profile_cv_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='detail',
        ),
    ]
