# Generated by Django 3.1.2 on 2020-10-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0014_remove_education_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='time_line',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
