# Generated by Django 3.1.2 on 2020-10-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0017_programing_language_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_cv',
            name='lang',
            field=models.ManyToManyField(blank=True, related_name='my_language_programing', to='profile_cv.Programing_Language'),
        ),
        migrations.AddField(
            model_name='profile_cv',
            name='workflow',
            field=models.ManyToManyField(blank=True, related_name='my_workflow', to='profile_cv.WorkFlow'),
        ),
    ]
