# Generated by Django 3.1.2 on 2020-10-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0018_auto_20201002_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programing_language',
            options={'ordering': ('-created',), 'verbose_name': 'Programing language or tech'},
        ),
        migrations.AddField(
            model_name='profile_cv',
            name='interests',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='programing_language',
            name='lang',
            field=models.CharField(max_length=250, verbose_name='language or tech'),
        ),
    ]
