# Generated by Django 3.1.2 on 2020-10-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0019_auto_20201002_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Awards & Certifications',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='profile_cv',
            name='awards',
            field=models.ManyToManyField(blank=True, related_name='my_awards', to='profile_cv.Awards'),
        ),
    ]
